### PR TITLE
Support TTY-only mode

### PR DESCRIPTION
**Pull request by 414owen**
Closes https://github.com/clitic/kdam/issues/14

Happy to hear any suggestions.

### CODE REVIEW

**Comment by clitic** [comment]
Thanks for pr I will review it soon.

**Comment by clitic** [comment]
@414owen Can you also fix the examples.

**Comment by 414owen** [comment]
@clitic Unfortunately, when building the examples, I get a bunch of linker errors:

```
          /home/owen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.21.2/src/exceptions.rs:305:(.text._ZN88_$LT$pyo3..exceptions..PyUnicodeDecodeError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$15type_object_raw28_$u7b$$u7b$closure$u7d$$u7d$17h711f465aa962eedfE+0x8): undefined reference to `PyExc_UnicodeDecodeError'
```

**Comment by 414owen** [comment]
Thanks @clitic .

Any chance of a push to crates.io?

**Comment by clitic** [comment]
@414owen uploaded to crates.io

**Pull request merged**
